##############################
- block:
    - name: Install Alert Logic Agent on Debian/Ubuntu
      apt:
        deb: "{{ al_agent_pkg_url }}"
      tags: install_al_agent
      when: ansible_os_family == "Debian"

    - name: Install Alert Logic Agent on CentOS/RHEL/Amazon
      package:
        name: "{{ al_agent_pkg_url }}"
        state: present
      tags: install_al_agent
      register: install_result
      retries: 3
      until: install_result is success
      when:
        - ansible_os_family != "Debian"
        - ansible_os_family != "Suse"

    - name: Install Alert Logic Agent on Suse
      zypper:
        name: "{{ al_agent_pkg_url }}"
        state: present
      tags: install_al_agent
      register: install_result
      retries: 3
      until: install_result is success
      when: ansible_os_family == "Suse"