##############################
- set_fact: al_agent_provision_options="[]"

- set_fact: al_agent_provision_options="{{ al_agent_provision_options }} + [ \'--key \' + al_agent_registration_key ]"
  when: al_agent_registration_key is defined and al_agent_registration_key != "your_registration_key_here"

- name: Provision Alert Logic Agent
  command: "/etc/init.d/al-agent provision {{ al_agent_provision_options|join(' ') }}"
  notify:
    - restart al-agent
  tags: provision_al_agent
  when: not al_agent_for_imaging and agent_provisioned.stat.exists == false and al_agent_provision_options != "[]"

- name: Provision Alert Logic Agent - for Imaging
  command: "/etc/init.d/al-agent provision {{ al_agent_provision_options|join(' ') }}"
  tags: provision_al_agent
  when: al_agent_for_imaging and agent_provisioned.stat.exists == false and al_agent_provision_options != "[]"
